AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >
    kenmyo-application-server

    Application server for kenmyo, used as an edge server to
    authenticate users and forwarding request to corresponding
    services

Parameters:
    StageName:
        Type: String
        AllowedValues:
            - Prod
            - Staging
    CognitoUserPool:
        Type: String

Globals:
    Function:
        Timeout: 3
        Runtime: nodejs8.10

Resources:

    AppServerApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref StageName
            DefinitionBody:
                swagger: 2.0
                info:
                    title: Kenmyo Application Server
                schemes:
                    - https
                securityDefinitions:
                    Cognito:
                        type: apiKey
                        name: x-kenmyo-user-id
                        in: header
                        x-amazon-apigateway-authtype: COGNITO_USER_POOLS
                        x-amazon-apigateway-authorizer:
                            type: COGNITO_USER_POOLS
                            providerARNs:
                                - !Ref CognitoUserPool
                paths:
                    /kenmyo.json:
                        options:
                            responses:
                                "200":
                                    headers:
                                        Access-Control-Allow-Headers:
                                            type: string
                                        Access-Control-Allow-Methods:
                                            type: string
                                        Access-Control-Allow-Origin:
                                            type: string
                            summary: CORS support
                            x-amazon-apigateway-integration:
                                type: mock
                                requestTemplates:
                                    application/json: |
                                        {
                                            "statusCode": 200
                                        }
                                responses:
                                    "default":
                                        statusCode: "200"
                                        responseParameters:
                                            method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-kenmyo-user-id'"
                                            method.response.header.Access-Control-Allow-Methods: "'*'"
                                            method.response.header.Access-Control-Allow-Origin: "'*'"
                                        responseTemplates:
                                            application/json: |
                                                {}
                        get:
                            responses:
                                "200": {}
                            security:
                                - Cognito: []
                            x-amazon-apigateway-integration:
                                type: aws_proxy
                                httpMethod: POST
                                uri: !Join
                                    - ""
                                    - - 'arn:aws:apigateway:'
                                      - !Ref AWS::Region
                                      - ':lambda:path/2015-03-31/functions/'
                                      - !GetAtt AppServerFunction.Arn
                                      - /invocations
    AppServerFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: dist/
            Handler: app.handler
            Environment:
                Variables:
                    KENMYO_ENV: !Ref StageName
            Events:
                AppServer:
                    Type: Api
                    Properties:
                        Path: /kenmyo.json
                        Method: get
                        RestApiId: !Ref AppServerApi

Outputs:

    AppServerApi:
        Description: "API Gateway endpoint URL for Application Server"
        Value: !Sub "https://${AppServerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/kenmyo.json"

    AppServerFunction:
        Description: "Application Server Lambda Function ARN"
        Value: !GetAtt AppServerFunction.Arn

    AppServerFunctionIamRole:
        Description: "Implicit IAM Role created for Application Server function"
        Value: !GetAtt AppServerFunctionRole.Arn
